sudo: required
language: python
virtualenv:
  system_site_packages: true
python:
- '3.5'
install:
- pip install -r requirements.txt
script:
- pytest
- coverage run test/test_mapykoB.py
after_success:
- coveralls
after_script: cd ~
deploy:
  provider: pypi
  user: andzl
  password:
    secure: KqvlDq4chSRUnHBMXzVJj6uWunaxqKkwTLuwHqej1P/r64AxaMnbtxSwmCQerFf7HQNif77P+7LZootx+eD7hYz+nsqLul5Lg5KTQjiktUVOnFFiQOjg5SJYNsdnum0/E44UowBzgD7xfZHFY8AsndKGfOBOjI6xDetEhgQjBBFk97zTVo2h+ENbKskBTPhesYaGeB/PzajHNwtmElEqiEbuEIOPg3dOURrz7J4GWb89JUiXiKGnvhqkQDxPqTaxSbCk7u7cH0hDUdsljpNkzjmCou6CW+DA/p4HK0gSKi80Jk2ZLfvb1z2QQYEWZb0m/VSi2JLqzShuCtwkq4tspe9mkUSaRedPAfBuMnuoRalAMpdHpSErnbvqaZLrRcHNMRXZ76LmeK/q0VCfzslPHeV1GCe7PcFC9hMfhMy+Uu6GEuK4k+GkO+GfP7M+dNbPUCAGLRN4FUp80sISkQOLVOm+d13RSeOqfnANY5k4VQEPIDhxpEYxCJzyvsyS+LHq8ijCvj3kqWIQHqSqFdi+GMmiNWiXAmTDKPs9724AjRVJ4BLuaZvBtE+wl5eWPb4NSAYMSV3cRhEuSIZBxJWMNNnzn7S3tyMZYOIau79L2Dr4YLzwW8G47N1mpN36P3SgtRr46nwvTTNLMGJYd2/EekBQ5+vJ4102W6YUQeffxjE=
